### ISSUE TITLE
C++: Html Export Crash

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1090]
On Windows with 0.99.7, CT crashes when I do an HTML export:

1) I select any node
2) Export->Export To HTML
3) Select the folder
4) It immediately crashes.

At the selected destination, I end up with a folder named NodeName_HTML, containing just 3 empty subfolders: EmbeddedFiles, images, res. I've tried this with numerous nodes (top level, lowest level, etc).  Every node I've tried causes the immediate crash.

**Comment by txe** [comment]
I just tried and it was OK. Can you start cherrytree from MSYS2 console, so you can see the log output?

**Comment by metal450** [comment]
Interesting - so I actually do my building in a virtual machine (I don't have msys2 installed on my *actual* Windows machine).  If I run it from the msys console on the VM, it exports successfully & doesn't crash.  So it only seems to be crashing on my "regular" machine (which doesn't have msys).

Is there any other way to get logging, on my non-msys machine where I'm able to reproduce the crash?

**Comment by txe** [comment]
Hm, I copied the built version into the portable folder and started it from there, still no issue.
There is no logging to a file yet, I'll add.

**Comment by metal450** [comment]
Sure, let me know then & I'll test again :)

**Comment by txe** [comment]
I added a rotating log file for windows, you can find it in the config directory.

**Comment by metal450** [comment]
Odd, rebuilding now (with msys2_prepare_standalone.sh) never completes.  Seems to get stuck running tests:

![2020-08-06_14 54 47](https://user-images.githubusercontent.com/1877409/89586573-d001ea80-d7f4-11ea-9eaa-4894a891c8a9.png)

**Comment by metal450** [comment]
I was still able to get the .exe built tho (just the tests didn't finish).

One thing: I'd suggest/request that the log be in a different location, for the same reason as we recently discussed with the database vs database backups (config directory file is part of syncing/external backups, but logs would be better to exclude).

It looks like the log doesn't write anything at the point of the crash.  Here's the contents of the log:

```
[2020-08-06 14:58:54.556] [gtk] [critical] Class::register_derived_type(): base_query.type_name is NULL.
[2020-08-06 14:58:54.557] [   ] [debug] C:\Users\Metal450\AppData\Local\cherrytree\config.cfg parsed
[2020-08-06 14:58:56.688] [   ] [debug] Node name: Denmark SIM Card
```
...Where I actually did the export/crash at 15:00 (later than the last log message)

**Comment by txe** [comment]
I'll run html import to see what logs it outputs.
I put logs in the config directory because it's easier to open the directory by cherrytree menu command, but I see your point.
I'm trying to fix the issue with test, just have no idea why it has got broken.

**Comment by metal450** [comment]
Well, how about: logs could be there if there's a checkbox in the options to disable them?  That's maybe a better solution, then they're easy to find, but can also be turned off for regular usage :)

**Comment by txe** [comment]
I fixed tests though they are still slow on Win, they take about 10 sec to finish.
I added few log outputs for html export, maybe it will give a general understanding what is going on. You also can add more logs by yourself, e.g. in `CtExport2Html::node_export_to_html`.
The current file log is a temporary measure, it will be redone to be more convenient

**Comment by metal450** [comment]
> I fixed tests 

Gotcha - I can confirm, build completes now :)  (However, side note - the issue I was discussing with guispen in #1032 is actually still present - aka the bundle produced by the script cannot actually be run; instead, I build with the script, then take the .exe and copy it to the bundle I download from giuspen.com)

> though they are still slow on Win, they take about 10 sec to finish.

Yeah, building for me on Windows is overall actually incredibly long (like >20min).  Maybe it's because I'm building in a VM. That's why I haven't done so much work/debugging on the Windows side, it's impractically time-consuming for each little try :/

> I added few log outputs for html export, maybe it will give a general understanding what is going on.

The only message it shows (within minutes of the crash) is: 

```
[2020-08-06 16:12:01.246] [   ] [debug] CtExport2Html::prepare_html_folder: start
```

That's the end of the log.

**Comment by metal450** [comment]
I'll add some more logs & do another test, hang tight (waiting for 20min build ;) )

**Comment by metal450** [comment]
The crash is on `fs::copy_file(styles_css_original, styles_css_filepath);`  in `CtExport2Html::prepare_html_folder()`.  The line before it passes `fs::path styles_css_original = fs::path(fs::get_cherrytree_datadir()) / fs::path("data") / "styles3.css";`, & a log just before `copy_file` is the last one to appear in the log file.

**Comment by metal450** [comment]
I might have an idea what this relates to.

When I was setting up cherrytree, I was trying to figure out where its config was saved, so I could move it to the dir where I have my system backups (by means of a symlink).  At first I found its config was in C:\Users\Metal450\AppData\Roaming\cherrytree, but then after a while I realized settings were no longer being updated there - instead, it now seemed to be C:\Users\Metal450\AppData\Local\cherrytree.  I've been chaging/messing around with a lot of versions as I learn how to use it, move over my content, test various builds, etc, so I'm not exactly sure when or why it changed - but I recall that one of those directories had a css file in it, which I'm guessing might have gotten moved somewhere along the process.  So that's probably WHY it's crashing.

As for the solution: maybe just a check if that file is there, & warn or recreate it if missing?  (Not sure how it gets created in the first place - i.e. by installer or the application itself).

**Comment by txe** [comment]
Thanks, it now be much easier to fix,

> I'll add some more logs & do another test, hang tight (waiting for 20min build ;) )
I'm not sure why you rebuild the whole project. If you change only one .cc file, `make` will build only that one, so it will take 30 seconds or so.

**Comment by metal450** [comment]
Ahhhh, duh, you're right.  Somehow I thought I had to run the script in order to get an exe that could be run standalone, aka not from msys2.  But I guess I can just build normally & reuse the previous bundle.  Much better :)

**Comment by txe** [comment]
I fixed the crash caused moving files and disabled the log into the file on Win
