### ISSUE TITLE
Table of Contents Not Saving

### ISSUE THREAD

**Issue by puddlecheese** [giuspen/cherrytree#1484]
**Version, Operative system**
0.99.29
Windows 10 64-Bit
Windows Version: 20H2
OS Build: 19042.685

**Describe the bug**
After inserting a Table of Contents and saving the CherryTree document (SQL), upon closing and re-opening CherryTree, the Table(s) of Contents that was just added is gone. If multiple Table of Contents have been added to multiple nodes, the file is saved, and then CherryTree closed and re-opened, the Table of Contents will be gone on multiple nodes, even if they are read-only.

**To Reproduce**
I have yet to find a rhyme or reason as to why this is occurring. It has occurred across multiple versions of CherryTree. The only hint that might prove useful is that I have A LOT of nodes, and multiple layers of sub-nodes, with color-coded text. The issue seems to become more frequent as more nodes and sub-nodes are added. I essentially insert table of contents for each node that has sub-nodes (Or each node that must be expanded to reveal additional nodes).

Primary Node(TOC) -> SubNode1(TOC) -> SubNode1/2/3/4/5(Color-coded text)

A way to reproduce this might be to paste lorem ipsum into various nodes and sub-nodes with ToCs on each of the nodes with sub-nodes under it.

Sorry I don't have more specific information on reproducibility! Maybe this is only an issue with larger documents?

Thank you!

**Comment by giuspen** [comment]
I will try and reproduce/have a thought what could cause it

**Comment by puddlecheese** [comment]
I realized something that might be useful information.

In Preferences/Special Characters, I have "Chars for Table of Content" as ">>>>", as I wanted everything to look uniform.

Just wanted to post this in the off-chance it might be helpful for reproducing the issue!

Thanks again!

**Comment by giuspen** [comment]
Could you try https://www.giuspen.com/software/cherrytree_0.99.29+2.exe.7z ? (after download and extract basically put the exe beside cherrytree.exe in the portable bundle and double click on cherrytree_0.99.29+2.exe to run (not cherrytree.exe)).
I think I fixed it but your feedback would help

**Comment by puddlecheese** [comment]
I can check after work. Thank you for investigating!

**Comment by puddlecheese** [comment]
Had some time to test. Initially, seemed like that did the trick, but after further testing, the issue still seems to be present, unfortunately.

**Comment by puddlecheese** [comment]
I don't know if this helps at all, but I've been trying to see if there's a workaround, and have noticed that inserting a table of contents no longer applies subsequent characters per node level.
---
1. I had removed all special characters from PREFERENCES/SPECIAL CHARACTERS/ except the following three: ☐☑☒
2. My Chars for Table of Content were ">>>>", as mentioned above, I wanted them to be uniform.
3. In testing the Table of Content deletion issue above, I tried resetting the Special Characters list to default. All default special characters are now listed there.
4. I then pressed the default button on Chars for Table of Content, which were defaulted to: ▸•◇▪
5. New Tables of Content now only show the first character (▸), and do not update the symbol per node layer / indent. All layers show "▸".
---
I don't know if this is related to the issues above, but felt it might be worth pointing out, just in case!

**Comment by puddlecheese** [comment]
Update: It only seems to happen in SQL. If I save the file as XML, the issue with Table of Contents does NOT seem to occur, at least, not yet!

**Comment by giuspen** [comment]
Can you try to "File--Save as" the sqlite document and use the new one and report how it goes there?

**Comment by puddlecheese** [comment]
> 
> 
> Can you try to "File--Save as" the sqlite document and use the new one and report how it goes there?

1. I just noticed that when I am adding new tables of contents, the little "*" that appears near the file's name to indicate a change has been made to the document DOES NOT appear.
2. I then tried your suggestion. I added new ToCs, then used Save As. The program became unresponsive for a bit, and then the file name changed to the new file name, indicating that the Save As was successfully processed.
3. Opening CherryTree after using Save As resulted in the ToCs being retained / saved.
4. On the new file name version after Save As, inserting new ToCs results in same behavior specified in 1. New ToCs do not appear to be saved.
5. It looks like you would have to use Save As every time for SQL to have the ToCs save to the file.

**Comment by giuspen** [comment]
1. That is what I fixed in the test version I gave you, I was hoping you would test that

**Comment by jonathonmckay** [comment]
I am also having this problem. Was going to raise an issue, then found this one.
Was using v 1.3.0, upgraded to 1.4.0. Problem still happens.
File being saved as Multiple Files in Folder Structure.

For me, this happens if the node is blank, I add a TOC and nothing else. It's like the act of adding the TOC doesn't flag the node as changed or something.
If I type some text, then add the TOC, it _seems_ to save fine.

**Comment by giuspen** [comment]
I will try to reproduce and get back.

**Comment by giuspen** [comment]
@jonathonmckay I did some testing but could not reproduce.
Could you please test https://www.giuspen.net/software/cherrytree_1.4.0.0+64_win64_portable.7z or https://www.giuspen.net/software/cherrytree_1.4.0.0+64_win64_setup.exe and report if you still see the issue?
In case the issue is still there, please describe step by step what I should do in order to reproduce it.

**Comment by jonathonmckay** [comment]
I tested the +64 version you linked above, problem still happens.

I will try to describe exactly how this happens to me:
The node I'm making the TOC on is rich text, completely empty. It is a 3rd level node. It has three nodes under it. Each of those nodes have multiple headings of various levels, and no sub nodes.
When making the TOC, I select "Insert --> Insert TOC and Header Collapsors...", then I select Selected Node and Subnodes. The TOC itself is made without a problem.

- If the node is completely blank, I insert the TOC, then save, the node changes are lost when I re-load.
- If the node is completely blank, I insert the TOC and then add some additional text, then save, the node changes are lost when I re-load.
- If I add some text so the node is not completely blank, I insert the TOC, then save, the node changes are saved and reloaded correctly.

**Comment by giuspen** [comment]
I was able to reproduce and I believe I fixed it. I will link the newer test build tomorrow or the day after so that you can confirm that it is indeed fixed.

**Comment by jonathonmckay** [comment]
I believe it is fixed.

I was having trouble telling at first. It seemed to be fixed, but then I closed and reloaded CherryTree, and it was broken again. But then I noticed that my old pinned task bar icon was launching it from a different path than the new shortcut (old one was in "mingw64\bin", new one is in "ucrt64\bin". Is this for a new backend layer or something?)
Once I fixed my taskbar pinned icon and startup shortcut, it seems to be working properly. 

I can add a TOC to a blank node, save, and reload, and it comes back. (I've also noticed the re-loads are faster than they used to be).
