### ISSUE TITLE
 accented characters

### ISSUE THREAD

**Issue by a-asar** [giuspen/cherrytree#1644]
The accented characters are not displayed, but my language requires them (French). I searched in the menus and in the manual but found nothing. Would it be possible to integrate them, or to propose a way to do it?
Thank you!

**Comment by mimecry** [comment]
what version are you using? i think it has been fixed since 0.99.34

**Comment by a-asar** [comment]
Thanks !
Indeed I had an old version. However I updated and it still doesn't work. Is there a special manipulation to do?

**Comment by mimecry** [comment]
seems fine to me unless i'm missing something 
![image](https://user-images.githubusercontent.com/10742312/115709401-608c5500-a39b-11eb-924d-60c2b5597861.png)

**Comment by a-asar** [comment]
More precisely, it works when I copy and paste, but not when I type those characters directly on the keyboard. And copying and pasting them elsewhere is not very comfortable for note taking ;)
(I took care to restart the computer (I'm on windows) but that didn't solve the problem).

**Comment by mimecry** [comment]
hmm i can type accented characters fine, although i'm using a software solution and not a keyboard with built in accented characters

**Comment by giuspen** [comment]
@a-asar are you using the default font or you changed it? Can you play with the fonts in the preferences dialog tab fonts and see if you find one that displays correctly non ASCII characters?

**Comment by ciranus** [comment]
@a-asar + which operating system ?

**Comment by a-asar** [comment]
Thanks to both of you! I am currently using Windows 10.
I hadn't changed the default font, so on your advice I tested several others, but I haven't found one that works when I type on the keyboard yet. My keyboard is a bepo, could this have an impact?

**Comment by ciranus** [comment]
I don't use windows, but it looks likes a keyboard configuration issue.
Do you confirm everything is OK when you type text in any other application ?

**Comment by a-asar** [comment]
Yes, I confirm ! It's the first time I have this problem.

**Comment by ciranus** [comment]
The first time since what ? A cherrytree update ? Other configuration modification ? (keyboard?)

**Comment by kadersin** [comment]
I have the same issue as well.  I'm using a french canadian keyboard on Windows 10, with CherryTree version 0.99.46.  The keyboard layout in CherryTree is the english one, when for all other applications it is french canadian.  Is CT forcing the use of the english keyboard layout?

**Comment by julienbusset** [comment]
Hi, I have the same issue with the portable version of cherrytree 0.99.53 on Windows 10.
I’m using a portable keyboard layout "bépo fr" you can find here: [https://bepo.fr/wiki/Portable_Keyboard_Layout](https://bepo.fr/wiki/Portable_Keyboard_Layout)
It seems cherrytree detects the key hit (the vertical bar stop blinking), but nothing appears at least for these characters : éèà^çîâêôÉÀÈ…’
So if I type "Élecrticité à gôgô…" in Notepad++ I get this:
![image](https://github.com/giuspen/cherrytree/assets/8694143/91773fa5-8b06-4f01-b004-ee9cf90ad83a)
and in cherrytree I get this:
![image](https://github.com/giuspen/cherrytree/assets/8694143/189c602b-0458-4df2-b551-13145f901726)

Thanks !

**Comment by giuspen** [comment]
I suspect it may be a GTK3 issue on windows rather than a cherrytree issue.
It would be a cherrytree issue if the keyboard combination that you use to insert such characters is captured for another use, but I would expect something to happen in that case/the connected action.
You can try and have a look at the preferences dialog, tab keyboard shortcuts, and look at the defined keyboard shortcuts (that you can disable).
It may help if you try to build and run cherrytree from the source code as descibed on https://github.com/giuspen/cherrytree#building-cherrytree-on-windows and report if anything is printed on the terminal when it fails to enter the character.

**Comment by giuspen** [comment]
If I understand correctly, I don't need any particular HW to try this BEPO layout, I'll try to understand and use it and see if I can reproduce in my Windows 10

**Comment by julienbusset** [comment]
Exactly. Here is the link to download the portable layout: https://download.tuxfamily.org/dvorak/windows/1.1rc2/pkl-bepo-1.1rc2.zip
It’s on the website I mentioned previously. Don’t hesitate to ask me if I can help.
Thank you!!

**Comment by julienbusset** [comment]
As mentioned above, I use the **portable version** of cherrytree 0.99.53: have you tried with the portable version?
But… Have I just read "1.0.0"? Congrats!!!
So I tried with cherrytree_1.0.0.0_win64_portable: I encounter the same issue.
By the way, at home I also use a BÉPO layout with cherrytree, but everything installed with the Windows installers, and everything works fine.

**Comment by FredislandCocci10** [comment]
**CherryTree v1.4.0 - Windows 10 Pro - FRENCH KEYBOARD**

I'm having exactly the same problem: it's not possible, for example, to enter accented capital letters. For example, Alt-0201 should display É. But it has no effect.

I also tried using software that allows you to display these accented capital letters via keyboard shortcuts, but the problem persists: the accented capital letters aren't displayed. However, I have no problem with accented lowercase letters directly accessible from the French keyboard. Likewise, accented capital letters display without issue if inserted via copy and paste.

This is the first time I've encountered this very annoying problem, but I'm confident a solution will be found quickly because CherryTree is a superb editor.

**Comment by FredislandCocci10** [comment]
Thanks @julienbusset for being faster than me 😊 (« Merci mec 😁 ! »). For English keyboard users, here is a summary table of access to French characters (on Windows):

![Image](https://github.com/user-attachments/assets/0d6598af-4b54-4843-a955-22644ca11c2c)

The method is native to Windows and can therefore be used on all software and input fields. In short, it works **everywhere**, even in a simple console:

![Image](https://github.com/user-attachments/assets/ae86d887-e80b-4901-84ab-714941838c5c)
And once again, thank you @giuspen for your excellent work on CherryTree.

Regards
Fred

**Comment by giuspen** [comment]
Hello @julienbusset , @FredislandCocci10 , it's weird  but it's not working for me on my Windows 11.
I tried on Notepad and the terminal (and also on firefox, this very text entry)

![Image](https://github.com/user-attachments/assets/53b29e78-735e-4767-bb53-10245c75e57a)

**Comment by FredislandCocci10** [comment]
@giuspen There is no reason why it should not work since it is a native Windows facility to be able to enter UNICODE characters in order to access the characters of other languages ​​on any system. I made you a small animated screenshot to properly perform the input process as explained by JulienBasset : 

![Image](https://github.com/user-attachments/assets/51021c6d-1952-4810-b830-7b78240bb84f)

The following link may also help you :
[https://www.johndcook.com/blog/2008/08/17/three-ways-to-enter-unicode-characters-in-windows/](url)
