### ISSUE TITLE
Search in Current Node & Find in Multiple Nodes... not find some alternative numbers or text randomly

### ISSUE THREAD

**Issue by VarinderMick** [giuspen/cherrytree#2444]
**Version, Operative system**
Windows 7

**Describe the bug**
I try to use Both > **Search in Current Node** & **Find in Multiple Nodes** but results are not normal see screenshots attached.

**To Reproduce**
please paste following text in some new nodes

999*
777777777777
777777
54545454
343434
545454
9999999999999999999999
700078967007896
y
t
y
ey
t
yt
r
ytr
yt
opopoppoopoppopopoppopoppopopppooopopop
[11](file:///C:/0000pics/2012_06_07_2429501_500/55/PhotoAlbum/images/5499_pixiv-qxdt-princess-knight_22.jpg)
opopoppioiuioppopopopoooppopo

I found that above error in results are due to the presence of Table, image, latexbox, Codebox in RTF node. (update to recreate the error)
### Steps to reproduce the behavior:
create RTF node with above text and must have a Table, or  image, or latexbox, or Codebox (update to recreate the error)

1. use Both > **Search in Current Node** & **Find in Multiple Nodes**
2. Find 54 , 77, 777, op, 999
3. See error results shown in screenshots and
4.  also in table the results are not as per data repeated in table see next post for this.

**Screenshots**
![pic-000214](https://github.com/giuspen/cherrytree/assets/122196218/96e9e495-436c-4801-a35d-1b2e263f746b)
![pic-000215](https://github.com/giuspen/cherrytree/assets/122196218/03baa35b-a98f-4462-a0cc-6cf617d109ef)
![pic-000216](https://github.com/giuspen/cherrytree/assets/122196218/440d3395-b7ca-4098-b1f0-e2769d53e211)
![pic-000217 part 1](https://github.com/giuspen/cherrytree/assets/122196218/1f1c9270-fabf-4671-a2c9-c56cf3f63ba7)
![pic-000217 part 2](https://github.com/giuspen/cherrytree/assets/122196218/5380e95b-8b46-4476-b731-e5c359c17fd9)

**Comment by VarinderMick** [comment]
**Updated post:** -----------------
I found that above error in results are due to the presence of Table, image, latexbox, Codebox in RTF node.
if I remove all of these then search results are fine. And in table the search is not as per data repeated in table as I try to find 'fg' it shows only one but in table are 3 'fg'

![table result not ok](https://github.com/giuspen/cherrytree/assets/122196218/7179ba8d-49bd-4e9f-a004-3f570e696d87)
![errors are due to these](https://github.com/giuspen/cherrytree/assets/122196218/be0e7fd9-a748-453b-9709-7e5f9533b9aa)
![without table etc results are fine](https://github.com/giuspen/cherrytree/assets/122196218/afd52c68-23fb-4783-9e99-3c60fcbcb779)

**Comment by giuspen** [comment]
Hi @VarinderMick are you using latest version 1.0.4?
Could you attach a test document to the ticket or send me privately? (mail in Help->About dialog)

**Comment by VarinderMick** [comment]
Hi Giuspen, Thanks for your quick response.
I am going to send you the file by email as unable to attach here.
Regards imvm
FYI:
yes I am using latest 1.0.4 portable.
the file is attached for your testing.
I paste the same text block before each of the elements (Table, latexbox, Codebox) image not used as you add image yourself after first block and paste text after it.

The text document is attached for your investigation.
and Thanks a lot for CherryTree

Text block is as below: (Random text)

999*
777777777777
777777
54545454
343434
545454
9999999999999999999999
700078967007896
y
t
y
ey
t
yt
r
ytr
yt
opopoppoopoppopopoppopoppopopppooopopop

opopoppioiuioppopopopoooppopo

**Comment by VarinderMick** [comment]
Hi Giuspen,

Please find the attached test file.
and my suggestions/(request to add features) are :


  1.  add file or folder path by drag and drop.
  2.  add picture (show pictures like jpg png) from hard disk picture file path/link (not like embedded in Cherrytree)


I try to test the software to use, I use it long long ago for short periods of time.
now I try to use it and test to see is it working for search and found these concerns. But I like the most is the table feature which is very good as it includes sorting and add OR move row columns as required. Only issue with table is with search in table data needs to be highlighted as rich text but work around is there as I found copy table in a text node and search 😉 .




Thanks,
Varinder


________________________________

**Comment by giuspen** [comment]
Ho @VarinderMick sorry I'm a bit slow to follow up because I'm completing v1.1.0 changes before writing to the translators.
I haven't received an email can you look in help--about dialog for my private email and send me the test file?

**Comment by giuspen** [comment]
Thanks for your report @VarinderMick and for submitting the test document. This is now fixed, the fix will be in upcoming v1.1.0. If you would like to test the fix before the new release is issued and report feedback please let me know and I will prepare a test portable windows version

**Comment by giuspen** [comment]
Thanks @VarinderMick please download https://www.giuspen.net/software/cherrytree_1.0.4.0+63_win64_portable.7z - this is effectively v1.1.0 pre-release - and report if it works as expected now

**Comment by VarinderMick** [comment]
Thanks @giuspen, I just check it for quick, it now search ok but not inside table (even 1 table if it contain same data value in different cells) while I put 2 tables it does not get the results for multiple table as well inside single table and not highlight the second table location properly, and **latex block not inserted** with this test version, get error for dvipng.exe..... libkvzaar-z.dll not found.

![table search location and data highlight error](https://github.com/giuspen/cherrytree/assets/122196218/9cba5231-b8fc-4ca8-9b31-a88455b8d707)

![Pic-000641 on 07-03](https://github.com/giuspen/cherrytree/assets/122196218/fe49316e-d6e8-4218-a2d2-40066fc5331c)

**Comment by VarinderMick** [comment]
Hi,  @giuspen, latex block and table search line position highlight and all data inside table not work properly. latest results. table in row 28 but not in 31 and full table is in one row, so may be it highlight all 3 67 in table one by one somehow. if I make a longer table I will never find any thing as it show one line result without highlight.

![pic-000224](https://github.com/giuspen/cherrytree/assets/122196218/c3bf4825-808f-46fc-bae4-a6a77a139bd5)
![pic-000225](https://github.com/giuspen/cherrytree/assets/122196218/d64f3174-2a9e-4ace-804f-c27af6839f1d)

**Comment by giuspen** [comment]
Thanks @VarinderMick I fixed the missing dll and re-uploaded the portable bundle.
Not highlighting the table cell and also not distinguiching table cells is a known issue also reported in https://github.com/giuspen/cherrytree/issues/2155 I have to support that

**Comment by VarinderMick** [comment]
still have issue as per screenshots if tables like shown below

![not ok if tables](https://github.com/giuspen/cherrytree/assets/122196218/f61f8394-5560-436b-9ade-dffb5d7683b9)
![search not ok if table is there](https://github.com/giuspen/cherrytree/assets/122196218/b2a90f6f-bf54-40af-a1d2-8f5fe9b5bf3a)

**Comment by giuspen** [comment]
Nice testing @VarinderMick I will come back with a fix. I decided to implement also the search inside of the table cells and code boxes as you are so kind to test thoroughly I will use your help, likely delaying the release of v1.1.0 of about a week

**Comment by VarinderMick** [comment]
Hi, @giuspen, Thanks for your kind response and happy to test, please take a look at issue-3 of #2454 if possible.

**Comment by giuspen** [comment]
please @VarinderMick test https://www.giuspen.net/software/cherrytree_1.0.4.0+pre110_win64_portable.7z where also the search in codeboxes and tables has been implemented

**Comment by VarinderMick** [comment]
now it perfectly search in tables also. 
**Thanks and respect for your efforts!**

(can you please take a look at #2454 to link file/url/folder/image with preview links by drag/drop at any line of note)

**Comment by giuspen** [comment]
Thanks for your testing @VarinderMick - I will look at the other ticket after the release which is running late
